language: node_js
branches:
  only:
  - production
deploy:
  provider: heroku
  app: metis-portal
  on:
    branch: production
  api_key:
    secure: SKDXgS2xwEoZQYtLSsRKiIhnZm0blAQA9UIBpRPB/cQVv3Js9bU9kiJFuOZG3KHFkZIb/j/O12ZvELOJBss6VzrkFSrVk7Jx1ClEFOG7fQoWe9uQHS1Q0ZCTXtdhdBzclooVEeWfFaImV6PT+LTzK1tj326u8Ae5mmM9+BKBiCZmq55MJP84npAb/e3fQ5ZyI1iWses73jInw/6g7tdQ97Lo5LiiKInYJGq/cKrfuAYCtULJxBs5UbE3XUadrkQbMQdQMufp3kMAqMOM7E1Yj9pVL/iuzDYGC9zejiZnKGP4ibK4nlcRP247SSlV6hkrPnZTek7RF60eS93pJWcspA0oeCC1YhSMZbErYL68f0cA04AHfFDnV+L6GEmpZCwWWhR4dorXYdJyIBXi8PbDASUBZpNMe6teNae1gSIDbZrLz1DyDzrDumkc2P8vsMPdqFWRp+/01/J5mYvurTR3TsF9XIKtipkDnoeFY3X6RTtuZPk269+g1Qx+jGJqKT7FrPm1DSHt7nkRmOi9DOdDS7ddd+EgSvuoNqavvWOl1r0bI4JvgmrZEMZJyTNrVtGdrf/5mithj9rn7AUaY/vQ194QkVyvQo/MPMsUBktgAJfUcWo5z1oTryswNf4hkAcdjQbDRxylkvDKZFD4ZH6JNav4OjXwGqqQxSmyg4u3T5M=
